### ISSUE TITLE
scipy.stats chisqprob fails to import

### ISSUE THREAD

**Issue by jenzopr** [brentp/combined-pvalues#16]
Hi Brent,

`comb-p region_p` fails with a recent scipy version since `stats.chisqprob` is deprecated (https://docs.scipy.org/doc/scipy-0.19.1/reference/generated/scipy.stats.chisqprob.html).

They suggest to use `stats.distributions.chi2.sf` instead.
If you like, I can prepare a PR, but I might not have enough insight to know where and how code has to be changed except from the import statements.

Best,
Jens

**Comment by jenzopr** [comment]
It seems to be removed completely in scipy 1.0.0.

Here is a workaround: https://github.com/statsmodels/statsmodels/issues/3931

**Comment by brentp** [comment]
thanks for reporting. I've just pushed a fix for this.

**Comment by jenzopr** [comment]
Great! Did you upload to pypi? I can then initiate a rebuild in bioconda.

**Comment by brentp** [comment]
it's up now as v0.48

**Comment by jenzopr** [comment]
Cool! 
My bad with Pypi: I just saw that I pull the source from GH. Great that you also created a new tag 👍

**Comment by brentp** [comment]
no problem. thanks very much for keeping the bioconda recipe up-to-date!
