### ISSUE TITLE
raise Exception('need header in p-value file to run filter')

### ISSUE THREAD

**Issue by Biojenifer** [brentp/combined-pvalues#22]
Hi!

I am running -comb p pipeline:

comb-p pipeline -c 4 --seed 1e-3 --dist 1000 -p $OUT_PREFIX --annotate hg19 $BEDFILE

My bed file is composed of 4 columns: chrom start end p_val (sorted by chromosome and start position)

The pipeline runs until it uses filter.py, giving me this error:

 Could you please give me some advice?
Thanks

**Comment by brentp** [comment]
did you try adding a header?

**Comment by Biojenifer** [comment]
Yes, but when I add a header bedtools fails:

raise ProcessException(cmd)
toolshed.files.ProcessException: bedtools intersect -b /scratch/3627075/tmpqyx80li0    -a mybedfile.bed -wo

I tried adding this header:

chrom start end p-value (tab separated)


Thanks,
Jenifer
________________________________
De: Brent Pedersen <notifications@github.com>
Enviado: martes, 4 de febrero de 2020 4:16
Para: brentp/combined-pvalues <combined-pvalues@noreply.github.com>
Cc: brea iglesias jenifer <jenifer.brea@rai.usc.es>; Author <author@noreply.github.com>
Asunto: Re: [brentp/combined-pvalues] raise Exception('need header in p-value file to run filter') (#22)


did you try adding a header?

**Comment by brentp** [comment]
you'll probably have to do without --annotate
