### ISSUE TITLE
Errors related to threading when running under Python 2.7

### ISSUE THREAD

**Issue by epikris** [brentp/combined-pvalues#25]
When run under Python 2.7 (to try to work around #21), comb-p produces the following error:

```
File "~/.conda/envs/p27/lib/python2.7/site-packages/cpv-0.50.3-py2
.7.egg/cpv/_common.py", line 161, in wrapper
    def wrap(self, timeout=threading.TIMEOUT_MAX):
AttributeError: 'module' object has no attribute 'TIMEOUT_MAX'
```

(error message edited to replace home directory with ~ )

**Comment by brentp** [comment]
I won't be able to continue to maintain python2. If you have trouble with python3, I will try to adress any issues (aside from --anno which would require too much porting).
