### ISSUE TITLE
Manhattan Plot's chromosomes ordered as characters

### ISSUE THREAD

**Issue by PhilBoileau** [brentp/combined-pvalues#32]
Hello! When running `comb-p pipeline`, I've found that the resulting manhattan plot's x-axis is ordered as a character vector instead of numerically (example attached). Note that I'm providing a sorted .bed file in which the chromosome column is also sorted as a character vector. This seems odd, but providing a .bed file in which the chromosomes are sorted numerically throws an error.

Based on the example provided in the readme, this isn't the desired behaviour for this plotting function. Any guidance would be appreciated.

![all_cell_common manhattan](https://user-images.githubusercontent.com/8812813/96352025-02418b00-1075-11eb-9180-11e9d0a9040f.png)

**Comment by annekristin** [comment]
I have just noticed the same issue, and I see it is a year since this was first posted. Is this a bug, or am I doing something wrong?

**Comment by brentp** [comment]
I just pushed a fix for this and tagged v0.50.5

**Comment by PhilBoileau** [comment]
Thanks, @brentp!
