### ISSUE TITLE
Issues running pipeline.py - no output/output is blank document

### ISSUE THREAD

**Issue by cewim** [brentp/combined-pvalues#40]
Hello,

I'm using combined-pvalues to look for DMRs in a set of human DNA methylation data. My input file is a tab-separated .txt file with columns "chr," "start," "end," and "p-val." Data are sorted ascending by chromosome and then by position, as shown below:

```
chrom	start	end	p_val
chr1	69591	69591	0.885264690250204
chr1	796328	796328	0.208967752727527
chr1	800083	800083	0.56272437061776
chr1	812539	812539	0.377711739687804
chr1	834183	834183	0.683163176817808
```

I'm running the code below to use the pipeline.py script to identify DMRs:

```
python cpv\pipeline.py -c 4 --seed 0.05 --dist 1000 -p comb_p_CMV_SESAME_EWAS_MA_output --region-filter-p 0.01 --region-filter-n 2 comb_p_CMV_SESAME_EWAS_MA.txt
```

When this is run, there is no output document. When I add `> try.txt` to the end of the line, the output is a blank document.

I am at a loss for why this is happening, and I would be grateful for any assistance you could provide.

**Comment by brentp** [comment]
you specified `comb_p_CMV_SESAME_EWAS_MA_output` as the output prefix. The relevant output files will start with that. YOu can see the readme for more details.

**Comment by cewim** [comment]
Thank you for your swift response. I did refer to the README and also reached out to more experienced Python users before raising this issue. They were able to confirm, as I noted in my original comment, that the output file is not appearing in any directory on my machine. Additionally, the script does not appear to be working for very long before moving back to the prompt. I am wondering if there is an issue with how I am running the code.

Do you see any issue with the code as written? Would you recommend trying to implement the pipeline step-by-step?

Thank you very much. As a beginner Python user, I appreciate your patience with me on this matter.

**Comment by brentp** [comment]
Oh, you can't run cpv/pipeline.py you should run `python setup.py install`, then run `comb-p`

**Comment by cewim** [comment]
Thank you. I did try this, and the setup script ran. However, I still get the error "'comb-p' is not recognized as an internal or external command, operable program, or batch file" or "python: can't open file 'comb-p' [Errorno 2] No such file or directory." Again, I am on a Windows machine, if it helps.

**Comment by brentp** [comment]
I don't know how to use windows, but you don't run `python comb-p` it should be installed where your python installed binaries go.
You can also try, from the combined-pvalues source directory to run `python cpv/comb-p`
